name: PharBuilder

on: push

jobs:
  build:
    name: PharBuilder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download pharbuilder-rs
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          file: pharbuilder
          repo: NetherGamesMC/pharbuilder-rs
          token: ${{ secrets.ng_token }}
      - name: Build
        run: |
          sudo chmod +x pharbuilder
          ./pharbuilder -i . -o InvMenu.phar
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: InvMenu
          path: InvMenu.phar
